"""
Pydantic models for the IRIS self-healing pipeline.

HealingDiagnosis: output from the MCP self_healer agent (DIAGNOSE phase).
HealingCandidate: a prompt mutation awaiting human approval (GATE phase).
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field


class HealingDiagnosis(BaseModel):
    """
    Structured output from the self_healer ADK agent's DIAGNOSE phase.
    Contains everything the Python pipeline needs to generate a candidate prompt.
    """
    candidate_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Failure cluster from pattern_detector
    failure_cluster: dict = Field(default_factory=dict)  # raw cluster JSON from pattern_detector
    query_type: str
    agent_name: str
    failing_span_ids: list[str] = Field(default_factory=list)
    hallucination_rate: float = 0.0  # 0.0–1.0

    # Real failing examples (input/output/violation/score) pulled from live traces.
    # These drive mutation + validation — no fabricated stubs.
    failing_examples: list[dict] = Field(default_factory=list)

    # Current prompt retrieved from Phoenix
    current_prompt_name: str
    current_prompt_text: str = ""
    current_prompt_version: str | None = None
    prompt_version_count: int = 0

    # Failure examples logged to Phoenix dataset
    dataset_name: str = ""
    examples_logged: int = 0

    # Gemini's analysis of WHY the failures occurred (the "textual gradient seed")
    failure_analysis: str = ""


class HealingCandidate(BaseModel):
    """
    A prompt mutation candidate generated by the Python pipeline.
    Awaits human approval before being promoted to production in Phoenix.
    """
    candidate_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Source diagnosis
    diagnosis: HealingDiagnosis

    # Prompt diff
    old_prompt_text: str
    new_prompt_text: str
    injected_constraint: str  # the specific clause added
    mutation_rationale: str   # why this constraint addresses the failures

    # Validation results (before promotion)
    validation_score_before: float | None = None  # mean score on failing examples with old prompt
    validation_score_after: float | None = None   # mean score on failing examples with new prompt
    improvement_score: float | None = None        # after - before
    validation_passed: bool = False

    # Phoenix tracking
    phoenix_prompt_version_id: str | None = None  # set after deployment
    phoenix_dataset_name: str | None = None
    experiment_id: str | None = None

    # Lifecycle
    status: Literal["pending", "approved", "rejected", "auto_approved", "deployed", "failed"] = "pending"
    approved_at: datetime | None = None
    deployed_at: datetime | None = None
    rejected_at: datetime | None = None
    rejection_reason: str | None = None
